name: Upload Package
description: Uploads unity package to pckgs.io

inputs:
  package_folder:
    description: 'Folder to compress'
    required: true
  access_token:
    description: 'Access token for authorization'
    required: true
  is_public:
    description: 'Set to true to make the package public'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
